### ISSUE TITLE
Fatal error when product that is part of a Mix and Match subscription is deleted

### ISSUE THREAD

**Issue by JRyven** [kathyisawesome/wc-mnm-satt-bridge#8] opened 2020-10-23 13:25 UTC
When using:
- Version 2.0.2 of wc-mnm-satt-bridge plugin
- Version 1.10.4 of Mix-and-Match
- Version 3.1.18 of WooCommerce All Products For Subscriptions
- Version 4.6.1 of WooCommerce

If I visit WooCommerce > Subscriptions, a fatal error is output:

`
Fatal error: Uncaught Error: Call to a member function get_type() on boolean in /DIRPATHREDACT/woocommerce-all-products-for-subscriptions/includes/class-wcs-att-product.php:119 
Stack trace: 
#0 /DIRPATHREDACT/woocommerce-all-products-for-subscriptions/includes/product/class-wcs-att-product-schemes.php(119): WCS_ATT_Product::supports_feature(false, 'subscription_sc...') 
#1 /DIRPATHREDACT/woocommerce-all-products-for-subscriptions/includes/integrations/class-wcs-att-integration-pb-cp.php(760): WCS_ATT_Product_Schemes::get_subscription_schemes(false) 
#2 /DIRPATHREDACT/woocommerce-all-products-for-subscriptions/includes/integrations/class-wcs-att-integration-pb-c
p.php(1887): WCS_ATT_Integration_PB_CP::set_bundled_product_subscription_schemes(false, Object(WC_Product_Mix_and_Match)) 
#- in /DIRPATHREDACT/woocommerce-all-products-for-subscriptions/includes/class-wcs-att-product.php on line 119
`

If seems that the product object is not yet extant when WooCommerce All Products For Subscriptions attempts to access the product object as the result of some behavior that wc-mnm-satt-bridge plugin undertakes.

**Comment by helgatheviking** [comment] 2020-10-24 16:31
Hi James... thanks for reporting this. This will pretty much be a duplicate of what I sent you via support, but wanted to have it here for reference.

The way I was able to reproduce this was to create a Mix and Match subscription. And then to _delete_ one of the products (not from the subscription order, but from WooCommerce entirely). 

It's not clear to my why your website is showing a product ID of 0 (I temporarily manipulated the template to show `$item->get_product_id();`)  when I saw a product ID in the order item meta table of your database. 

![image](https://user-images.githubusercontent.com/507025/97086924-8c44a300-15e3-11eb-8baf-a508c326d544.png)

But it does work out that if the product no longer exists `wc_get_product()` will return `false`. And so then All Products for Subscriptions manipulations will fail because they expect an object... which is the error you've reported.

I've opened up an issue with SomewhereWarm, but it's a private repo, so linking for my own reference:
https://github.com/somewherewarm/woocommerce-all-products-for-subscriptions/issues/301

**Comment by JRyven** [comment] 2020-10-28 16:34
Thank you very much! The pre-release version of the somewhere warm software works as expected with your bridge plugin. Thanks for the speedy action! I'll look forward to the official release from somewhere warm in the coming days. 

I'm not sure if you're done with this issue report, so I'm just leaving a comment here. I consider the issue resolved on my end!

**Comment by helgatheviking** [comment] 2020-10-28 17:38
Great, thanks James. I'm glad that's working. I will close this issue and I think we've closed out the issue in support as well.

**Closed as completed by helgatheviking** 2020-10-28 17:38 UTC
